apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-BMW
spec:
  replicas: 2 # Example: Use fewer replicas in development
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:dev # Example: Use a development-specific Docker image
